/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const BusinessProfile = IDL.Record({
  'principal' : IDL.Principal,
  'contactInfo' : IDL.Text,
  'subscriptionExpiry' : IDL.Opt(Time),
  'isBlocked' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'kycPhoto' : IDL.Opt(ExternalBlob),
  'updatedAt' : Time,
  'kycStatus' : ApprovalStatus,
  'address' : IDL.Text,
  'verifyImage' : IDL.Opt(ExternalBlob),
  'kycDocs' : IDL.Opt(ExternalBlob),
});
export const RewardStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'redeemed' : IDL.Null,
});
export const Reward = IDL.Record({
  'id' : IDL.Text,
  'status' : RewardStatus,
  'principal' : IDL.Principal,
  'expiresAt' : Time,
  'rewardEntered' : IDL.Bool,
  'createdAt' : Time,
  'wasManuallyAdded' : IDL.Bool,
  'lastUpdated' : Time,
  'businessName' : IDL.Text,
  'businessLocation' : IDL.Text,
  'lastActivityTime' : Time,
  'redemptionActivityCount' : IDL.Nat,
  'testRewardActivityCount' : IDL.Nat,
  'isTestReward' : IDL.Bool,
  'points' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'seller' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'isBlocked' : IDL.Bool,
  'name' : IDL.Text,
  'role' : UserRole,
});
export const TokenPurchase = IDL.Record({
  'user' : IDL.Principal,
  'business' : IDL.Principal,
  'timestamp' : Time,
  'expiry' : Time,
  'amount' : IDL.Nat,
});
export const SuggestedMatch = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'isPartial' : IDL.Bool,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const BusinessData = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveKYC' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createBusinessProfile' : IDL.Func([BusinessProfile], [], []),
  'getAllPendingKYC' : IDL.Func([], [IDL.Vec(BusinessProfile)], ['query']),
  'getAvailableRewardPool' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
  'getBusinessDetails' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BusinessProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMyBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
  'getMyLeads' : IDL.Func([], [IDL.Vec(TokenPurchase)], ['query']),
  'getMyRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
  'getMyUnlockHistory' : IDL.Func([], [IDL.Vec(TokenPurchase)], ['query']),
  'getRevenueStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'subscriptionRevenue' : IDL.Nat,
          'tokenRevenue' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getRewardById' : IDL.Func([IDL.Text], [IDL.Opt(Reward)], ['query']),
  'getSuggestedMatches' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(SuggestedMatch)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'rejectKYC' : IDL.Func([IDL.Principal], [], []),
  'renewSubscription' : IDL.Func([IDL.Nat, Time], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchBusinessObjectsByPrefix' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BusinessData)],
      ['query'],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'unlockBusiness' : IDL.Func([IDL.Principal, IDL.Nat, Time], [], []),
  'updateBusinessProfile' : IDL.Func([BusinessProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const BusinessProfile = IDL.Record({
    'principal' : IDL.Principal,
    'contactInfo' : IDL.Text,
    'subscriptionExpiry' : IDL.Opt(Time),
    'isBlocked' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'kycPhoto' : IDL.Opt(ExternalBlob),
    'updatedAt' : Time,
    'kycStatus' : ApprovalStatus,
    'address' : IDL.Text,
    'verifyImage' : IDL.Opt(ExternalBlob),
    'kycDocs' : IDL.Opt(ExternalBlob),
  });
  const RewardStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'redeemed' : IDL.Null,
  });
  const Reward = IDL.Record({
    'id' : IDL.Text,
    'status' : RewardStatus,
    'principal' : IDL.Principal,
    'expiresAt' : Time,
    'rewardEntered' : IDL.Bool,
    'createdAt' : Time,
    'wasManuallyAdded' : IDL.Bool,
    'lastUpdated' : Time,
    'businessName' : IDL.Text,
    'businessLocation' : IDL.Text,
    'lastActivityTime' : Time,
    'redemptionActivityCount' : IDL.Nat,
    'testRewardActivityCount' : IDL.Nat,
    'isTestReward' : IDL.Bool,
    'points' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'seller' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'isBlocked' : IDL.Bool,
    'name' : IDL.Text,
    'role' : UserRole,
  });
  const TokenPurchase = IDL.Record({
    'user' : IDL.Principal,
    'business' : IDL.Principal,
    'timestamp' : Time,
    'expiry' : Time,
    'amount' : IDL.Nat,
  });
  const SuggestedMatch = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'isPartial' : IDL.Bool,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const BusinessData = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveKYC' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createBusinessProfile' : IDL.Func([BusinessProfile], [], []),
    'getAllPendingKYC' : IDL.Func([], [IDL.Vec(BusinessProfile)], ['query']),
    'getAvailableRewardPool' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
    'getBusinessDetails' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMyBusinessProfile' : IDL.Func(
        [],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'getMyLeads' : IDL.Func([], [IDL.Vec(TokenPurchase)], ['query']),
    'getMyRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
    'getMyUnlockHistory' : IDL.Func([], [IDL.Vec(TokenPurchase)], ['query']),
    'getRevenueStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'subscriptionRevenue' : IDL.Nat,
            'tokenRevenue' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getRewardById' : IDL.Func([IDL.Text], [IDL.Opt(Reward)], ['query']),
    'getSuggestedMatches' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(SuggestedMatch)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'rejectKYC' : IDL.Func([IDL.Principal], [], []),
    'renewSubscription' : IDL.Func([IDL.Nat, Time], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchBusinessObjectsByPrefix' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BusinessData)],
        ['query'],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'unlockBusiness' : IDL.Func([IDL.Principal, IDL.Nat, Time], [], []),
    'updateBusinessProfile' : IDL.Func([BusinessProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };