/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BusinessData {
  'id' : string,
  'name' : string,
  'address' : string,
}
export interface BusinessProfile {
  'principal' : Principal,
  'contactInfo' : string,
  'subscriptionExpiry' : [] | [Time],
  'isBlocked' : boolean,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'kycPhoto' : [] | [ExternalBlob],
  'updatedAt' : Time,
  'kycStatus' : ApprovalStatus,
  'address' : string,
  'verifyImage' : [] | [ExternalBlob],
  'kycDocs' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface Reward {
  'id' : string,
  'status' : RewardStatus,
  'principal' : Principal,
  'expiresAt' : Time,
  'rewardEntered' : boolean,
  'createdAt' : Time,
  'wasManuallyAdded' : boolean,
  'lastUpdated' : Time,
  'businessName' : string,
  'businessLocation' : string,
  'lastActivityTime' : Time,
  'redemptionActivityCount' : bigint,
  'testRewardActivityCount' : bigint,
  'isTestReward' : boolean,
  'points' : bigint,
}
export type RewardStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'redeemed' : null };
export interface SuggestedMatch {
  'id' : string,
  'name' : string,
  'address' : string,
  'isPartial' : boolean,
}
export type Time = bigint;
export interface TokenPurchase {
  'user' : Principal,
  'business' : Principal,
  'timestamp' : Time,
  'expiry' : Time,
  'amount' : bigint,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'isBlocked' : boolean,
  'name' : string,
  'role' : UserRole,
}
export type UserRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'seller' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveKYC' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'createBusinessProfile' : ActorMethod<[BusinessProfile], undefined>,
  'getAllPendingKYC' : ActorMethod<[], Array<BusinessProfile>>,
  'getAvailableRewardPool' : ActorMethod<[], Array<Reward>>,
  'getBusinessDetails' : ActorMethod<[Principal], [] | [BusinessProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMyBusinessProfile' : ActorMethod<[], [] | [BusinessProfile]>,
  'getMyLeads' : ActorMethod<[], Array<TokenPurchase>>,
  'getMyRewards' : ActorMethod<[], Array<Reward>>,
  'getMyUnlockHistory' : ActorMethod<[], Array<TokenPurchase>>,
  'getRevenueStats' : ActorMethod<
    [],
    { 'subscriptionRevenue' : bigint, 'tokenRevenue' : bigint }
  >,
  'getRewardById' : ActorMethod<[string], [] | [Reward]>,
  'getSuggestedMatches' : ActorMethod<[string, string], Array<SuggestedMatch>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'rejectKYC' : ActorMethod<[Principal], undefined>,
  'renewSubscription' : ActorMethod<[bigint, Time], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchBusinessObjectsByPrefix' : ActorMethod<[string], Array<BusinessData>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'unlockBusiness' : ActorMethod<[Principal, bigint, Time], undefined>,
  'updateBusinessProfile' : ActorMethod<[BusinessProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];